/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as MapRouteImport } from './routes/map'
import { Route as HeritageRouteImport } from './routes/heritage'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveIndexRouteImport } from './routes/archive.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as HeritageCategoryIdRouteImport } from './routes/heritage.$categoryId'
import { Route as ArchivePhotoIdRouteImport } from './routes/archive.$photoId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTaxonomyRouteImport } from './routes/admin.taxonomy'
import { Route as AdminPhotosRouteImport } from './routes/admin.photos'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminPhotosNewRouteImport } from './routes/admin.photos_.new'
import { Route as AdminPhotosPhotoIdEditRouteImport } from './routes/admin.photos_.$photoId.edit'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageRoute = HeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/archive/',
  path: '/archive/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const HeritageCategoryIdRoute = HeritageCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => HeritageRoute,
} as any)
const ArchivePhotoIdRoute = ArchivePhotoIdRouteImport.update({
  id: '/archive/$photoId',
  path: '/archive/$photoId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTaxonomyRoute = AdminTaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPhotosRoute = AdminPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPhotosNewRoute = AdminPhotosNewRouteImport.update({
  id: '/photos_/new',
  path: '/photos/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPhotosPhotoIdEditRoute = AdminPhotosPhotoIdEditRouteImport.update({
  id: '/photos_/$photoId/edit',
  path: '/photos/$photoId/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/heritage': typeof HeritageRouteWithChildren
  '/map': typeof MapRoute
  '/timeline': typeof TimelineRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/photos': typeof AdminPhotosRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/users': typeof AdminUsersRoute
  '/archive/$photoId': typeof ArchivePhotoIdRoute
  '/heritage/$categoryId': typeof HeritageCategoryIdRoute
  '/admin/': typeof AdminIndexRoute
  '/archive/': typeof ArchiveIndexRoute
  '/admin/photos/new': typeof AdminPhotosNewRoute
  '/admin/photos/$photoId/edit': typeof AdminPhotosPhotoIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/heritage': typeof HeritageRouteWithChildren
  '/map': typeof MapRoute
  '/timeline': typeof TimelineRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/photos': typeof AdminPhotosRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/users': typeof AdminUsersRoute
  '/archive/$photoId': typeof ArchivePhotoIdRoute
  '/heritage/$categoryId': typeof HeritageCategoryIdRoute
  '/admin': typeof AdminIndexRoute
  '/archive': typeof ArchiveIndexRoute
  '/admin/photos/new': typeof AdminPhotosNewRoute
  '/admin/photos/$photoId/edit': typeof AdminPhotosPhotoIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/heritage': typeof HeritageRouteWithChildren
  '/map': typeof MapRoute
  '/timeline': typeof TimelineRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/photos': typeof AdminPhotosRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/users': typeof AdminUsersRoute
  '/archive/$photoId': typeof ArchivePhotoIdRoute
  '/heritage/$categoryId': typeof HeritageCategoryIdRoute
  '/admin/': typeof AdminIndexRoute
  '/archive/': typeof ArchiveIndexRoute
  '/admin/photos_/new': typeof AdminPhotosNewRoute
  '/admin/photos_/$photoId/edit': typeof AdminPhotosPhotoIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/favorites'
    | '/heritage'
    | '/map'
    | '/timeline'
    | '/admin/comments'
    | '/admin/photos'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/archive/$photoId'
    | '/heritage/$categoryId'
    | '/admin/'
    | '/archive/'
    | '/admin/photos/new'
    | '/admin/photos/$photoId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/favorites'
    | '/heritage'
    | '/map'
    | '/timeline'
    | '/admin/comments'
    | '/admin/photos'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/archive/$photoId'
    | '/heritage/$categoryId'
    | '/admin'
    | '/archive'
    | '/admin/photos/new'
    | '/admin/photos/$photoId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/favorites'
    | '/heritage'
    | '/map'
    | '/timeline'
    | '/admin/comments'
    | '/admin/photos'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/archive/$photoId'
    | '/heritage/$categoryId'
    | '/admin/'
    | '/archive/'
    | '/admin/photos_/new'
    | '/admin/photos_/$photoId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  FavoritesRoute: typeof FavoritesRoute
  HeritageRoute: typeof HeritageRouteWithChildren
  MapRoute: typeof MapRoute
  TimelineRoute: typeof TimelineRoute
  ArchivePhotoIdRoute: typeof ArchivePhotoIdRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage': {
      id: '/heritage'
      path: '/heritage'
      fullPath: '/heritage'
      preLoaderRoute: typeof HeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/archive'
      fullPath: '/archive/'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/heritage/$categoryId': {
      id: '/heritage/$categoryId'
      path: '/$categoryId'
      fullPath: '/heritage/$categoryId'
      preLoaderRoute: typeof HeritageCategoryIdRouteImport
      parentRoute: typeof HeritageRoute
    }
    '/archive/$photoId': {
      id: '/archive/$photoId'
      path: '/archive/$photoId'
      fullPath: '/archive/$photoId'
      preLoaderRoute: typeof ArchivePhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/taxonomy': {
      id: '/admin/taxonomy'
      path: '/taxonomy'
      fullPath: '/admin/taxonomy'
      preLoaderRoute: typeof AdminTaxonomyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/photos': {
      id: '/admin/photos'
      path: '/photos'
      fullPath: '/admin/photos'
      preLoaderRoute: typeof AdminPhotosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/photos_/new': {
      id: '/admin/photos_/new'
      path: '/photos/new'
      fullPath: '/admin/photos/new'
      preLoaderRoute: typeof AdminPhotosNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/photos_/$photoId/edit': {
      id: '/admin/photos_/$photoId/edit'
      path: '/photos/$photoId/edit'
      fullPath: '/admin/photos/$photoId/edit'
      preLoaderRoute: typeof AdminPhotosPhotoIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminPhotosRoute: typeof AdminPhotosRoute
  AdminTaxonomyRoute: typeof AdminTaxonomyRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPhotosNewRoute: typeof AdminPhotosNewRoute
  AdminPhotosPhotoIdEditRoute: typeof AdminPhotosPhotoIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCommentsRoute: AdminCommentsRoute,
  AdminPhotosRoute: AdminPhotosRoute,
  AdminTaxonomyRoute: AdminTaxonomyRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPhotosNewRoute: AdminPhotosNewRoute,
  AdminPhotosPhotoIdEditRoute: AdminPhotosPhotoIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HeritageRouteChildren {
  HeritageCategoryIdRoute: typeof HeritageCategoryIdRoute
}

const HeritageRouteChildren: HeritageRouteChildren = {
  HeritageCategoryIdRoute: HeritageCategoryIdRoute,
}

const HeritageRouteWithChildren = HeritageRoute._addFileChildren(
  HeritageRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  FavoritesRoute: FavoritesRoute,
  HeritageRoute: HeritageRouteWithChildren,
  MapRoute: MapRoute,
  TimelineRoute: TimelineRoute,
  ArchivePhotoIdRoute: ArchivePhotoIdRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
