-- ═══════════════════════════════════════════════════════════════
-- Felix Lens (Felen) — Migration 005: Seed Photos
-- ═══════════════════════════════════════════════════════════════

-- Helper function to select category id by slug
CREATE OR REPLACE FUNCTION get_cat_id(p_slug text) RETURNS uuid AS $$
  SELECT id FROM heritage_categories WHERE slug = p_slug;
$$ LANGUAGE sql;

-- Helper function to select governorate id by slug
CREATE OR REPLACE FUNCTION get_gov_id(p_slug text) RETURNS uuid AS $$
  SELECT id FROM governorates WHERE slug = p_slug;
$$ LANGUAGE sql;

-- Insert 20 mock photos
INSERT INTO photos (
  title_ar, title_en, description_ar, photographer, source, year, date_taken,
  governorate_id, category_id, lat, lng, aspect, status, featured
) VALUES
  (
    'بيوت صنعاء القديمة عند الغروب',
    'Old Sana''a at dusk',
    'لقطة أرشيفية توثق النمط المعماري الفريد لمدينة صنعاء القديمة بقمرياتها الشهيرة وتداخل مبانيها الطينية عند الغروب.',
    'فهد الظرافي',
    'الأرشيف الخاص',
    1974,
    '1974-06-14',
    get_gov_id('sanaa'),
    get_cat_id('architecture'),
    15.369445,
    44.191006,
    'landscape',
    'published',
    true
  ),
  (
    'ناطحات سحاب شبام',
    'Skyscrapers of Shibam',
    'توثيق لمعجزة العمارة الطينية في وادي حضرموت - مدينة شبام التاريخية ناطحة السحاب الأولى في العالم.',
    'فهد الظرافي',
    'الأرشيف الخاص',
    1985,
    '1985-06-14',
    get_gov_id('hadramout'),
    get_cat_id('architecture'),
    15.933610,
    48.784626,
    'portrait',
    'published',
    true
  ),
  (
    'قمرية زجاجية ملونة',
    'Stained-glass qamariya',
    'تفاصيل فنية دقيقة لقمرية صنعانية تقليدية مصنوعة من الجبس والزجاج الملون تعكس الضوء الساقط في بيت قديم.',
    'فهد الظرافي',
    'الأرشيف الخاص',
    2010,
    '2010-06-14',
    get_gov_id('sanaa'),
    get_cat_id('architecture'),
    15.369445,
    44.191006,
    'square',
    'published',
    true
  ),
  (
    'أشجار دم الأخوين',
    'Dragon blood trees',
    'أشجار دم الأخوين النادرة والمميزة في جزيرة سقطرى، رمز الطبيعة والتنوع الحيوي الفريد لليمن.',
    'فهد الظرافي',
    'الأرشيف الخاص',
    2019,
    '2019-06-14',
    get_gov_id('socotra'),
    get_cat_id('architecture'),
    12.463400,
    53.823700,
    'landscape',
    'published',
    true
  ),
  (
    'جامع زبيد الكبير',
    'Great Mosque of Zabid',
    'تفاصيل معمارية ونقوش خطية بديعة من محراب جامع مدينة زبيد التاريخية، مركز العلم والثقافة الإسلامية.',
    'فهد الظرافي',
    'الأرشيف الخاص',
    1998,
    '1998-06-14',
    get_gov_id('hodeidah'),
    get_cat_id('manuscripts'),
    14.797760,
    42.954540,
    'portrait',
    'published',
    true
  ),
  (
    'قلعة القاهرة في تعز',
    'Cairo Castle, Taiz',
    'منظر عام لقلعة القاهرة التاريخية الرابضة على سفح جبل صبر والمطلة على مدينة تعز القديمة.',
    'فهد الظرافي',
    'الأرشيف الخاص',
    1968,
    '1968-06-14',
    get_gov_id('taiz'),
    get_cat_id('architecture'),
    13.578900,
    44.020900,
    'landscape',
    'published',
    true
  ),
  (
    'صانع الجنابي في سوق الملح',
    'Jambiya maker at Salt Souk',
    'حرفي يمني يعمل بدقة على نحت وتزيين مقبض جنبية فضية تقليدية في قلب سوق الملح بصنعاء القديمة.',
    'فهد الظرافي',
    'الأرشيف الخاص',
    1979,
    '1979-06-14',
    get_gov_id('sanaa'),
    get_cat_id('crafts'),
    15.369445,
    44.191006,
    'portrait',
    'published',
    true
  ),
  (
    'نسيج تهامي',
    'Tihama weaving',
    'عملية نسيج يدوي تقليدي لحياكة المعاوز اللحجية والتهامية الشهيرة بألوانها الزاهية في الحديدة.',
    'فهد الظرافي',
    'الأرشيف الخاص',
    1982,
    '1982-06-14',
    get_gov_id('hodeidah'),
    get_cat_id('textiles'),
    14.797760,
    42.954540,
    'square',
    'published',
    true
  ),
  (
    'زامل جبلي في الأعراس',
    'Mountain zamil chant',
    'مجموعة من رجال القبائل يؤدون زاملاً جماعياً ترحيبياً خلال أحد الأعراس التقليدية في ريف إب.',
    'فهد الظرافي',
    'الأرشيف الخاص',
    1992,
    '1992-06-14',
    get_gov_id('ibb'),
    get_cat_id('zawamil'),
    13.966700,
    44.183300,
    'landscape',
    'published',
    true
  ),
  (
    'بائعة سمك في المكلا',
    'Fish seller in Mukalla',
    'لقطة عفوية لبائعة سمك تقليدية في سوق السمك المفتوح على ساحل مدينة المكلا بحضرموت.',
    'فهد الظرافي',
    'الأرشيف الخاص',
    1988,
    '1988-06-14',
    get_gov_id('hadramout'),
    get_cat_id('food'),
    15.933610,
    48.784626,
    'portrait',
    'published',
    true
  ),
  (
    'بورتريه شيخ من مأرب',
    'Portrait of a Marib elder',
    'بورتريه يظهر الملامح الأصيلة لشيخ يرتدي الجنبية وعصابة الرأس التقليدية في زيارة لصنعاء.',
    'فهد الظرافي',
    'الأرشيف الخاص',
    1971,
    '1971-06-14',
    get_gov_id('sanaa'),
    get_cat_id('crafts'),
    15.369445,
    44.191006,
    'portrait',
    'published',
    true
  ),
  (
    'طقس عرس صنعاني',
    'Sana''ani wedding ritual',
    'لقطة فنية تظهر تفاصيل نقش الحناء التقليدي واللباس المذهب للعروس الصنعانية في ليلة الغسل.',
    'فهد الظرافي',
    'الأرشيف الخاص',
    2004,
    '2004-06-14',
    get_gov_id('sanaa'),
    get_cat_id('rituals'),
    15.369445,
    44.191006,
    'landscape',
    'published',
    true
  ),
  (
    'خط ثلث على منبر',
    'Thuluth on a minbar',
    'تفاصيل النقش البارز لآيات قرآنية بخط الثلث البديع على منبر خشبي قديم في أحد مساجد الحديدة.',
    'فهد الظرافي',
    'الأرشيف الخاص',
    2001,
    '2001-06-14',
    get_gov_id('hodeidah'),
    get_cat_id('manuscripts'),
    14.797760,
    42.954540,
    'square',
    'published',
    true
  ),
  (
    'قصر سيئون',
    'Seiyun Palace',
    'الواجهة الخارجية المهيبة لقصر الكثيري الطيني الشهير بمدينة سيئون في وادي حضرموت.',
    'فهد الظرافي',
    'الأرشيف الخاص',
    1994,
    '1994-06-14',
    get_gov_id('hadramout'),
    get_cat_id('architecture'),
    15.933610,
    48.784626,
    'landscape',
    'published',
    true
  ),
  (
    'بيع البخور في سقطرى',
    'Frankincense sellers, Socotra',
    'نساء سقطريات يعرضن البخور واللبان السقطري النادر والمستخلص طبيعياً في سوق حديبو.',
    'فهد الظرافي',
    'الأرشيف الخاص',
    2016,
    '2016-06-14',
    get_gov_id('socotra'),
    get_cat_id('crafts'),
    12.463400,
    53.823700,
    'portrait',
    'published',
    true
  ),
  (
    'حكواتي في سوق عدن',
    'Storyteller, Aden souk',
    'لقطة نادرة لتجمع الأهالي والأطفال حول حكواتي شعبي يروي السير والقصص في حواري عدن القديمة.',
    'فهد الظرافي',
    'الأرشيف الخاص',
    1962,
    '1962-06-14',
    get_gov_id('aden'),
    get_cat_id('folktales'),
    12.785500,
    45.018700,
    'landscape',
    'published',
    true
  ),
  (
    'أطفال في زقاق صنعاني',
    'Children in a Sana''a alley',
    'براءة وابتسامات الأطفال اليمنيين أثناء لعبهم في أحد الأزقة الضيقة لمدينة صنعاء القديمة في السبعينات.',
    'فهد الظرافي',
    'الأرشيف الخاص',
    1977,
    '1977-06-14',
    get_gov_id('sanaa'),
    get_cat_id('folktales'),
    15.369445,
    44.191006,
    'portrait',
    'published',
    true
  ),
  (
    'مخطوطة فلكية زبيدية',
    'Zabidi astronomical manuscript',
    'صفحة نادرة من مخطوطة فلكية قديمة توضح حركة النجوم مكتوبة ومزينة باليد في مدارس زبيد العلمية.',
    'فهد الظرافي',
    'الأرشيف الخاص',
    2022,
    '2022-06-14',
    get_gov_id('hodeidah'),
    get_cat_id('manuscripts'),
    14.797760,
    42.954540,
    'square',
    'published',
    true
  ),
  (
    'بيت الفقيه في الفجر',
    'Bayt al-Faqih at dawn',
    'مشهد هادئ ومميز لمدينة بيت الفقيه التهامية التاريخية ومآذنها عند مطلع الفجر.',
    'فهد الظرافي',
    'الأرشيف الخاص',
    1990,
    '1990-06-14',
    get_gov_id('hodeidah'),
    get_cat_id('architecture'),
    14.797760,
    42.954540,
    'landscape',
    'published',
    true
  ),
  (
    'أزياء نسائية من ريدة',
    'Women''s costume, Raidah',
    'تفاصيل التطريز اليدوي الدقيق والنقوش الملونة للأثواب النسائية التقليدية التراثية في منطقة ريدة.',
    'فهد الظرافي',
    'الأرشيف الخاص',
    1986,
    '1986-06-14',
    get_gov_id('sanaa'),
    get_cat_id('textiles'),
    15.369445,
    44.191006,
    'portrait',
    'published',
    true
  );

-- Clean up helper functions
DROP FUNCTION get_cat_id(text);
DROP FUNCTION get_gov_id(text);
